#!/bin/bash
#set -x
clear
#######
###
### Made by Stephane HUC - <devs@stephane-huc.net>
###  alias ATP, ATP:MIUI, ATP:RedRice...
###
### thanks for explains :
#### http://www.chinaphonearena.com/forum/
###
### License: CC 0
###

EXEC=true
if ! ${EXEC}; then exit; fi

PWD="$(pwd)"
INC="${PWD}/inc"
DIR_LANG="${PWD}/lang" #&& echo $DIR_LANG
lang="${LANG:0:2}" #&& echo $LANG
#lang="en"
# link texts and titles variables
if [[ -f "${DIR_LANG}/titles.${lang}" ]]; then source "${DIR_LANG}/titles.${lang}"; else source "${DIR_LANG}/titles.en"; fi
if [[ -f "${DIR_LANG}/texts.${lang}" ]]; then source "${DIR_LANG}/texts.${lang}"; else source "${DIR_LANG}/texts.en"; fi

# link files needed
source "${INC}/config"

# link functions needed
#source "${INC}/dialog"
#source "${INC}/zenity"
source "${INC}/display"
source "${INC}/ADB_functions"
source "${INC}/functions"

# Launcher
if [[ $# -eq 0 ]]; then

    MTKZenyTux

else

    case "$1" in

        -f|-F|-flash)
            control_system
            detect_args "FLASH" "$2"
            FLASH "$2"
        ;;

        -h|-H|-\?|-help)
            display_help
        ;;

        -R|-reboot)
            adb_reboot_system
        ;;

        -RR|-reboot_recovery)
            adb_reboot_recovery
        ;;

        -root)
            control_system
            ROOT
        ;;

        -s|-S|-save)
            control_system
            detect_args "BACKUP" "$2"
            BACKUP "$2"
        ;;

        -unroot)
            control_system
            UNROOT
        ;;

        *)
            manage_fonts
            mssg=$(printf "${text_error_unknown_option}" "$1")
            display_error "${mssg}\n"
            press_any_key
            display_help
            exit 1
        ;;

    esac

fi
