#!/bin/bash

if ! ${EXEC}; then exit; fi

if [[ -z "${PWD}" ]]; then PWD="$(pwd)"; fi
if [[ -z "${INC}" ]]; then INC="${PWD}/inc"; fi

CONFIG="config.ini" # file to save some variables
DIR_CFG="${INC}/cfg/"
DIR_TOOLS="${PWD}/tools/"

###
# source config files needed
###
source "${DIR_CFG}/cfg_partitions"
source "${DIR_CFG}/cfg_SuperSU"
source "${DIR_CFG}/cfg_time"

###
# Arrays
###

# arrays to build informations colored
declare -a COLORS_NAME=('black' 'red' 'green' 'yellow' 'blue' 'magenta' 'cyan' 'white')
declare -a COLORS_VALUE=('0' '1' '2' '3' '4' '5' '6' '7')

#declare -a CFG

declare -A FILES_CHOOSED

declare -a GUIS=( 'd' 'dialog' 'z' 'zenity')

# arrays to build mapping informations
declare -a INFO_MAP
declare -a INFO_NAME=('name' 'size' 'addr' 'type' 'map')

# arrays to build menu
declare -a MENU_NAME=("BACKUP" "FLASH" "ROOT" "UNROOT" "REBOOT" "EXIT")
declare -a MENU_REBOOT=("RECOVERY" "SYSTEM")
declare -A MENU_TEXT
declare -A MENU_TEXT_REBOOT

# arrays to get MTD informations
declare -a MTD_ADDR
declare -a MTD_MAP
declare -a MTD_NAME
declare -a MTD_SIZE
declare -a MTD_TYPE
declare -a MTD_ADDR_BLOCK
declare -a MTD_ADDR_DEC
declare -a MTD_SIZE_BLOCK
declare -a MTD_SIZE_DEC

source "${DIR_CFG}/cfg_vid_pid"

###
# Int variables
###
declare -i CHOICE=0
declare -i CFG=0
declare -i DIALOG=0
declare -i INODE=4096
declare -i LOG=0
declare -i ZENITY=0

###
# String variables
###
adb_su=""

ANDROID_DEVICE=""
ANDROID_MODEL=""
ANDROID_PRODUCT=""
ANDROID_SERIAL=""

BCKP_PHONE="/sdcard/BACKUP/" # dir to backup into phone
DIR_CHOOSED=""
DIR_TMP="/tmp/"
DIR_SVG=""
DIR_SVG_DATED=""
FILE_CHOOSED=""
FILE_DUMCHAR="dumchar.info"
FILE_PARAM="${DIR_TOOLS}${FILE_DUMCHAR}"
GUI=""
HOME="/home/$USER"  #HOME=~
MODE=""
#PART_BCKP=""
SCRIPT_NAME=$0
SCRIPT_TMP_DIR="${DIR_TMP}${SCRIPT_NAME:2}/"

# Directories where are packages into device system
SYS_APP="/system/app/"
SYS_BIN="/system/xbin/"
SYS_ETC="/system/etc/"
