#!/bin/bash

# Packages names
SuperSU="Superuser.apk"
SU="su"
version="v2.13"
SSUD="99SuperSUDaemon"

# others vars - DONT TOUCH!
PWD=$(pwd)

# URL app
DL_SUPERSU="http://download.chainfire.eu/567/SuperSU/UPDATE-SuperSU-${version}.zip?retrieve_file=1"
URL_SUPERSU="http://download.chainfire.eu/supersu"

# Directories where are packages needed into your computer
DIR_Tools="${PWD}/tools/"
DIR_ARM="${DIR_Tools}UPDATE-SuperSU-${version}/arm/"
DIR_CMN="${DIR_Tools}UPDATE-SuperSU-${version}/common/"
DIR_SSU="${DIR_CMN}${SuperSU}"
DIR_SSUD="${DIR_CMN}${SSUD}"
DIR_SU="${DIR_ARM}${SU}"

# Directories where are packages into device system
SYS_APP="/system/app/"
SYS_BIN="/system/xbin/"
SYS_ETC="/system/etc/"

# VendorIDs
VID[0]="0bb4" # recognized as HTC (High Tech Computer Corp.)
VID[1]="2717" # Xiaomi
VID[2]="2717" # Xiaomi
VID[3]="2717" # Xiaomi

# ProductIDs
PID[0]="0c03" # recognized as Android Phone [Fairphone First Edition (FP1)]
PID[1]="1218" # Redmi PTP with USB Debug
PID[2]="1228" # Redmi UMS with USB Debug
PID[3]="1248" # Redmi MTP with USB Debug

# Partitions
PART_NAME[0]="android"
PART_NAME[1]="usrdata"

PART_TEXT[0]="system"
PART_TEXT[1]="data"

# files to saved by default
FILES[0]="uboot"
FILES[1]="bootimg"
FILES[2]="recovery"
FILES[3]="logo"
FILES[4]="android"
FILES[5]="usrdata"

# Others
count["name"]=${#text_menu_name[@]}
declare -a guis=('dialog', 'zenity')
declare -a info_map
declare -a info_name=('name' 'size' 'addr' 'type' 'map')
declare -a mtd_addr
declare -a mtd_map
declare -a mtd_name
declare -a mtd_size
declare -a mtd_type
declare -a mtd_addr_dec
declare -a mtd_size_dec

adb_su=""
config="config.ini" # file to save some variables
dir=""

BCKP_PHONE="/sdcard/"
DIR_SVG=""
DIR_SVG_DATED=""
FILE_TMP=""
FILE_TMP2=""
FILE_PARAM="${DIR_Tools}/dumchar.info"
FILE_SSU_ZIP="${DIR_Tools}UPDATE-SuperSU-${version}.zip"
GUI=""
HOME=~

day=$(date +"%d-%m-%Y")
now=$(date +"%d-%m-%Y_%H-%M-%S")

choice=0
CFG=0
DIALOG=0
INODE=4096
LOG=0
ZENITY=0
