#!/bin/bash

function display_detected() {

    # call: display_detected mssg
    local mssg=$(printf "$1\n" "$2");

    if [[ "${DIALOG}" -ne 0 ]]; then

        if [[ "${esc_seq}" ]]; then esc_seq="\e["; neutral=0; fi
        echo -e "${esc_seq};3${green}m${mssg}${esc_seq};${neutral}m"
        #echo -e "\Z${bold}\Z${green}${mssg}\Z${neutral}\Z${unbold}"

    elif [[ "${ZENITY}" -ne 0 ]]; then

        if [[ -z "${esc_seq}" ]]; then esc_seq="\e["; neutral=0; fi
        echo -e "${esc_seq};32m${mssg}${esc_seq};${neutral}m"

    else

        if [[ -z "${esc_seq}" ]]; then esc_seq="\e["; fi
        echo -e "${esc_seq};${green}m${mssg}${esc_seq};${neutral}m"

    fi

    write_file "log" "### Detected: ${mssg}"

    unset mssg

}

function display_error() {

    # call: display_error mssg
    local text

    if [[ "${DIALOG}" -ne 0 ]]; then

        text="\Z${bold}\Z${red}$1\Z${neutral}\Z${unbold}"
        text=$(printf "${text}" "$2")

        dialog_mssg "${text}" "${title_error}"


    elif [[ "${ZENITY}" -ne 0 ]]; then

        zenity_error "<span color=\"${red}\">${bold}$1${unbold}</span>" "$2"

    else

        if [[ -z "${esc_seq}" ]]; then esc_seq="\e["; fi
        text="${esc_seq}${bold};${red}m$1${esc_seq}${neutral};${unbold}m"
        printf "${text}" "$2"

    fi

    write_file "log" "### Error: $1"
    unset text

}

function display_files() {

    write_file "log" "$now ### $FUNCNAME: attempt to display files for choosing..."

    if [[ "${ZENITY}" -eq 1 ]]; then

        files=$( echos_files | zenity_list_files "${text_menu_files}" "${title_menu_files}" "${#mtd_name[@]}")

    fi

    if [[ "${DIALOG}" -eq 1 ]]; then

        echos_files

        display_detected "files: $files"

    fi

    if [[ "${files}" ]]; then
        write_file "log" "### $FUNCNAME: Files choosed: ${files[*]}";
    fi

}

function display_menu() {

    write_file "log" "$now ### $FUNCNAME: attempt to display menu..."

    while true; do
        choice=""

        if [[ "${ZENITY}" -ne 0 ]]; then

            choice=$( echos_menu | zenity_list "${text_welcome}" "${title_welcome}" "${count['name']}")

        elif  [[ "${DIALOG}" -ne 0 ]]; then

            #if [[ -f "${FILE_TMP}_menu.tmp" ]]; then rm -f "${FILE_TMP}_menu.tmp"; fi
            #if [[ -f "${FILE_TMP}" ]]; then rm -f "${FILE_TMP}"; fi

            echos_menu

            exec 3>&1;
            choice=$(dialog_menu "${text_welcome}" "${title_welcome}" "$(count ${text_menu_name[@]})")
            exec 3>&-;

            #if [[ -f "${FILE_TMP}_menu.tmp" ]]; then rm -f "${FILE_TMP}_menu.tmp"; fi
            #if [[ -f "${FILE_TMP}" ]]; then rm -f "${FILE_TMP}"; fi

            unset menu

        else

            printf "\n${title_menu}\n"

            PS3="${text_welcome} "
            select menu in "${text_menu_description[@]}"; do
                if [[ "$REPLY" == "q" || "$REPLY" == "Q" ]]; then
                    choice="${text_menu_name[${#text_menu_name[*]}]}"
                elif [[ -z "${text_menu_name[$REPLY]}" ]]; then
                    choice=""
                else
                    choice="${text_menu_name[$REPLY]}"
                fi
                break
            done

            unset menu

        fi

        # if choice exists, then run-it!
        if [[ "$choice" ]]; then

            key=$(array_search "${choice}" "${text_menu_name[@]}");

            if [[ -z "${key}" ]]; then unset choice; else "${choice}"; fi
            unset array key

            write_file "log" "### $FUNCNAME: choice: ${choice}"
        fi

    done

    if [[ $? -ne 0 ]]; then EXIT; fi

}

function display_mssg() {

    # call: display_mssg option title text sec
    #+ param sec is for DIALOG info
    local menu="$1" text="$2" title="$3" sec="$4"

    if [[ "${ZENITY}" -ne 0 ]]; then

        case "$menu" in
            i) zenity_info "${text}" "${title}" ;;
            n) zenity_notify "${text}" "${title}" ;;
            q) zenity_question "${text}" "${title}" ;;
        esac

    elif [[ "${DIALOG}" -ne 0 ]]; then

        case "$menu" in
            i)
                dialog_mssg "${text}" ;;
            q)
                dialog_yesno "${text}" "${title}"

                read=$(</tmp/dialog_yesno.tmp)
                if [[ -f /tmp/dialog_yesno.tmp ]]; then rm -rf /tmp/dialog_yesno.tmp; fi

            ;;
            *)  dialog_info "${text}" "${sec}" ;;
        esac

    else

        case "$menu" in
            q) echo -e "$2" "${text_yes_no}"; read ;;
            *) echo -e "$2" ;;
        esac

    fi

    write_file "log" "### Message: $2"

}

function echos_files() {

    write_file "log" "$now ### $FUNCNAME: Attempt ones echos to choose files..."

    i=1

    if [[ "${DIALOG}" -eq 1 ]]; then

        items=""
        for name in "${mtd_name[@]}"; do

            key=$(array_search "${mtd_name[$i]}" "${FILES[@]}")
            if [[ -n "$key" ]] ; then key="on"; else key="off"; fi

            items="${items} $i ${name} ${key}"

            let "i = $i + 1";
            unset key

        done

        files=$(dialog_list_files "${text_menu_files}" "${title_menu_files}" "${items}")

        display_detected "items: ${items}"
        unset items

    fi

    if [[ "${ZENITY}" -eq 1 ]]; then

        while [ $i -le $(count "${mtd_name[@]}") ]; do

            key=$(array_search "${mtd_name[$i]}" "${FILES[@]}");
            if [[ -n "${key}" ]]; then echo TRUE; else echo FALSE; fi

            echo "${mtd_name[$i]}"
            echo "${mtd_size[$i]}"
            echo "${mtd_addr[$i]}"
            echo "${mtd_map[$i]}"

            let "i = $i + 1";
            unset key

        done

    fi

    unset array i

}

function echos_menu() {

    write_file "log" "$now ### $FUNCNAME: Attempt ones echos to choose menu..."

    local -i i=1

    if [[ "${DIALOG}" -eq 1 ]]; then

        while [ $i -le $(count "${text_menu_name[@]}") ]; do

            menu+=("${text_menu_name[$i]}" "${text_menu_description[$i]}")

            let "i = $i + 1";

        done

        #display_detected "menu: ${menu}"

    else

        while [ $i -le $(count "${text_menu_name[@]}") ]; do
            echo "${text_menu_name[$i]}";
            echo "${text_menu_description[$i]}";
            let "i = $i + 1";
        done

    fi

	unset i

}
