#!/bin/bash

if ! ${EXEC}; then exit; fi

###
# file config: informations about VendorID and ProductID
###

## HTC (High Tech Computer Corp.) Dream / ADP1 / G1 / Magic / Tattoo
#0bb4:0c01
## HTC (High Tech Computer Corp.) Dream / ADP1 / G1 / Magic / Tattoo (Debug)
#0bb4:0c02
## HTC (High Tech Computer Corp.) Android Phone [Fairphone First Edition (FP1)]
#0bb4:0c03
## Xiaomi Redmi PTP with USB Debug
#2717:1218
## Xiaomi Redmi UMS with USB Debug
#2717:1228
## Xiaomi Redmi MTP with USB Debug
#2717:1248

# VendorIDs
VID[0]="0bb4" # recognized as HTC (High Tech Computer Corp.)
VID[1]="2717" # Xiaomi
