#!/bin/bash

if ! ${EXEC}; then exit; fi

###
# file config: get time informations
###

DAY=$(date +"%d-%m-%Y")
DAY_LOG=$(date +"%Y-%m-%d")
NOW=$(date +"%d-%m-%Y %H:%M:%S")
NOW_DIR=$(date +"%Y-%m-%d_%H:%M:%S")
